# Generated by Django 5.0.2 on 2024-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('', 'Selecione um sexo'), ('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Prefiro não informar'), ('4', 'Outro')], default='', max_length=100),
        ),
    ]
