# Generated by Django 5.0.2 on 2024-03-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='Clinic',
            new_name='clinic',
        ),
    ]
