# Generated by Django 5.0.2 on 2024-05-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='odontograma.medicalrecord'),
        ),
    ]
