# Generated by Django 5.0.2 on 2024-05-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0003_alter_procedure_medical_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='sifiles',
            new_name='sifilis',
        ),
    ]
